---
version: '3.3'
services:
    service1:
      build: ./service1
      image: ./service1:${APP_VERSION}
      ports:
      - target: 5000
        published: 5000
        protocol: tcp
      deploy:
        replicas: 2
    service2:
      build: ./service2
      image: ./service2:${APP_VERSION}
      ports:
      - target: 5001
        published: 5001
        protocol: tcp
      deploy:
        replicas: 2

...


